# Hotel Cancellation Prediction using differnt algorithm

In [ ]:
# Abhishek Saurabh (created by)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
hotel = pd.read_csv(r"hotel_bookings.csv")

In [5]:
hotel.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0                7/1/2015  
1                7/1/2015  
2                7/2/2015  
3                7/2/2015  
4                7/3/2015  

[5 rows x 32 columns]

In [6]:
hotel.describe()

is_canceled      lead_time  arrival_date_year  \
count  119390.000000  119390.000000      119390.000000   
mean        0.370416     104.011416        2016.156554   
std         0.482918     106.863097           0.707476   
min         0.000000       0.000000        2015.000000   
25%         0.000000      18.000000        2016.000000   
50%         0.000000      69.000000        2016.000000   
75%         1.000000     160.000000        2017.000000   
max         1.000000     737.000000        2017.000000   

       arrival_date_week_number  arrival_date_day_of_month  \
count             119390.000000              119390.000000   
mean                  27.165173                  15.798241   
std                   13.605138                   8.780829   
min                    1.000000                   1.000000   
25%                   16.000000                   8.000000   
50%                   28.000000                  16.000000   
75%                   38.000000                  23.000000   
max                   53.000000                  31.000000   

       stays_in_weekend_nights  stays_in_week_nights         adults  \
count            119390.000000         119390.000000  119390.000000   
mean                  0.927599              2.500302       1.856403   
std                   0.998613              1.908286       0.579261   
min                   0.000000              0.000000       0.000000   
25%                   0.000000              1.000000       2.000000   
50%                   1.000000              2.000000       2.000000   
75%                   2.000000              3.000000       2.000000   
max                  19.000000             50.000000      55.000000   

            children         babies  is_repeated_guest  \
count  119386.000000  119390.000000      119390.000000   
mean        0.103890       0.007949           0.031912   
std         0.398561       0.097436           0.175767   
min         0.000000       0.000000           0.000000   
25%         0.000000       0.000000           0.000000   
50%         0.000000       0.000000           0.000000   
75%         0.000000       0.000000           0.000000   
max        10.000000      10.000000           1.000000   

       previous_cancellations  previous_bookings_not_canceled  \
count           119390.000000                   119390.000000   
mean                 0.087118                        0.137097   
std                  0.844336                        1.497437   
min                  0.000000                        0.000000   
25%                  0.000000                        0.000000   
50%                  0.000000                        0.000000   
75%                  0.000000                        0.000000   
max                 26.000000                       72.000000   

       booking_changes          agent      company  days_in_waiting_list  \
count    119390.000000  103050.000000  6797.000000         119390.000000   
mean          0.221124      86.693382   189.266735              2.321149   
std           0.652306     110.774548   131.655015             17.594721   
min           0.000000       1.000000     6.000000              0.000000   
25%           0.000000       9.000000    62.000000              0.000000   
50%           0.000000      14.000000   179.000000              0.000000   
75%           0.000000     229.000000   270.000000              0.000000   
max          21.000000     535.000000   543.000000            391.000000   

                 adr  required_car_parking_spaces  total_of_special_requests  
count  119390.000000                119390.000000              119390.000000  
mean      101.831122                     0.062518                   0.571363  
std        50.535790                     0.245291                   0.792798  
min        -6.380000                     0.000000                   0.000000  
25%        69.290000                     0.000000                   0.000000  
50%        94.57500

In [7]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [8]:
hotel.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [9]:
hotel= hotel.drop(['company'],axis=1)    #its has maximum null value thats why removing it.

In [11]:
hotel= hotel.dropna(axis=0)                 # Removing all the rows which have missing values

In [12]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102894 entries, 3 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           102894 non-null  object 
 1   is_canceled                     102894 non-null  int64  
 2   lead_time                       102894 non-null  int64  
 3   arrival_date_year               102894 non-null  int64  
 4   arrival_date_month              102894 non-null  object 
 5   arrival_date_week_number        102894 non-null  int64  
 6   arrival_date_day_of_month       102894 non-null  int64  
 7   stays_in_weekend_nights         102894 non-null  int64  
 8   stays_in_week_nights            102894 non-null  int64  
 9   adults                          102894 non-null  int64  
 10  children                        102894 non-null  float64
 11  babies                          102894 non-null  int64  
 12  meal            

In [13]:
hotel.isnull().sum()                  #agian checking for any null value

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces 

In [14]:
hotel['hotel'].unique()      #checking the unique value in hotel

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [15]:
categorical_features = ['hotel','is_canceled','arrival_date_week_number','meal','country','market_segment',
                        'distribution_channel','is_repeated_guest','reserved_room_type','assigned_room_type',
                        'deposit_type','agent','customer_type','reservation_status','arrival_date_month']

In [16]:
hotel[categorical_features]=hotel[categorical_features].astype('category')

C:\Users\Abhishek saurabh\anaconda3\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [17]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102894 entries, 3 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype   
---  ------                          --------------   -----   
 0   hotel                           102894 non-null  category
 1   is_canceled                     102894 non-null  category
 2   lead_time                       102894 non-null  int64   
 3   arrival_date_year               102894 non-null  int64   
 4   arrival_date_month              102894 non-null  category
 5   arrival_date_week_number        102894 non-null  category
 6   arrival_date_day_of_month       102894 non-null  int64   
 7   stays_in_weekend_nights         102894 non-null  int64   
 8   stays_in_week_nights            102894 non-null  int64   
 9   adults                          102894 non-null  int64   
 10  children                        102894 non-null  float64 
 11  babies                          102894 non-null  int64   
 12  me

In [18]:
hotel['meal'].unique()

['BB', 'FB', 'HB', 'SC', 'Undefined']
Categories (5, object): ['BB', 'FB', 'HB', 'SC', 'Undefined']

In [19]:
y=hotel['is_canceled']                  # seperating the data set into feature and target value

In [20]:
y

3         0
4         0
5         0
7         0
8         1
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: is_canceled, Length: 102894, dtype: category
Categories (2, int64): [0, 1]

In [21]:
X = hotel.drop(['is_canceled','reservation_status_date'],axis=1)

In [23]:
X

hotel  lead_time  arrival_date_year arrival_date_month  \
3       Resort Hotel         13               2015               July   
4       Resort Hotel         14               2015               July   
5       Resort Hotel         14               2015               July   
7       Resort Hotel          9               2015               July   
8       Resort Hotel         85               2015               July   
...              ...        ...                ...                ...   
119385    City Hotel         23               2017             August   
119386    City Hotel        102               2017             August   
119387    City Hotel         34               2017             August   
119388    City Hotel        109               2017             August   
119389    City Hotel        205               2017             August   

       arrival_date_week_number  arrival_date_day_of_month  \
3                            27                          1   
4                            27                          1   
5                            27                          1   
7                            27                          1   
8                            27                          1   
...                         ...                        ...   
119385                       35                         30   
119386                       35                         31   
119387                       35                         31   
119388                       35                         31   
119389                       35                         29   

        stays_in_weekend_nights  stays_in_week_nights  adults  children  ...  \
3                             0                     1       1       0.0  ...   
4                             0                     2       2       0.0  ...   
5                             0                     2       2       0.0  ...   
7                             0                     2       2       0.0  ...   
8                             0                     3       2       0.0  ...   
...                         ...                   ...     ...       ...  ...   
119385                        2                     5       2       0.0  ...   
119386                        2                     5       3       0.0  ...   
119387                        2                     5       2       0.0  ...   
119388                        2                     5       2       0.0  ...   
119389                        2                     7       2       0.0  ...   

        assigned_room_type booking_changes deposit_type  agent  \
3                        A               0   No Deposit  304.0   
4                        A               0   No Deposit  240.0   
5                        A               0   No Deposit  240.0   
7                        C               0   No Deposit  303.0   
8                        A               0   No Deposit  240.0   
...                    ...             ...          ...    ...   
119385                   A               0   No Deposit  394.0   
119386                   E               0   No Deposit    9.0   
119387                   D               0   No Deposit    9.0   
119388                   A               0   No Deposit   89.0   
119389                   A               0   No Deposit    9.0   

       days_in_waiting_list customer_type     adr  \
3                         0     Transient   75.00   
4                         0     Transient   98.00   
5                         0     Transient   98.00   
7                         0     Transient  103.00   
8                         0     Transient   82.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

  

In [24]:
X_dum=pd.get_dummies(X,prefix_sep='-',drop_first=True) # converting  the data into dummy variable

In [25]:
X_dum

lead_time  arrival_date_year  arrival_date_day_of_month  \
3              13               2015                          1   
4              14               2015                          1   
5              14               2015                          1   
7               9               2015                          1   
8              85               2015                          1   
...           ...                ...                        ...   
119385         23               2017                         30   
119386        102               2017                         31   
119387         34               2017                         31   
119388        109               2017                         31   
119389        205               2017                         29   

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
3                             0                     1       1       0.0   
4                             0                     2       2       0.0   
5                             0                     2       2       0.0   
7                             0                     2       2       0.0   
8                             0                     3       2       0.0   
...                         ...                   ...     ...       ...   
119385                        2                     5       2       0.0   
119386                        2                     5       3       0.0   
119387                        2                     5       2       0.0   
119388                        2                     5       2       0.0   
119389                        2                     7       2       0.0   

        babies  previous_cancellations  previous_bookings_not_canceled  ...  \
3            0                       0                               0  ...   
4            0                       0                               0  ...   
5            0                       0                               0  ...   
7            0                       0                               0  ...   
8            0                       0                               0  ...   
...        ...                     ...                             ...  ...   
119385       0                       0                               0  ...   
119386       0                       0                               0  ...   
119387       0                       0                               0  ...   
119388       0                       0                               0  ...   
119389       0                       0                               0  ...   

        agent-510.0  agent-526.0  agent-527.0  agent-531.0  agent-535.0  \
3                 0            0            0            0            0   
4                 0            0            0            0            0   
5                 0            0            0            0            0   
7                 0            0            0            0            0   
8                 0            0            0            0            0   
...             ...          ...          ...          ...          ...   
119385            0            0            0            0            0   
119386            0            0            0            0            0   
119387            0            0            0            0            0   
119388            0            0            0            0            0   
119389            0            0            0            0            0   

        customer_type-Group  customer_type-Transient  \
3                         0                        1   
4                         0                        1   
5                         0                        1   
7                         0                        1   
8                         0                        1   
...                     ...                      ...   
119385                    0                        1   
1193

In [ ]:
#Splitting the data into train and test


In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test= train_test_split(X_dum,y, test_size=.25,random_state=40)

In [28]:
X_train

lead_time  arrival_date_year  arrival_date_day_of_month  \
62810          59               2017                         23   
60440          58               2016                         11   
118566        207               2017                         12   
65878         202               2017                          9   
103778         36               2016                         28   
...           ...                ...                        ...   
67049         233               2017                         27   
108930         48               2017                          1   
94019          25               2016                         29   
39004          62               2017                          1   
13463         145               2017                         16   

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
62810                         1                     1       2       0.0   
60440                         0                     2       2       0.0   
118566                        4                     6       2       0.0   
65878                         2                     1       2       2.0   
103778                        0                     4       2       0.0   
...                         ...                   ...     ...       ...   
67049                         2                     3       3       0.0   
108930                        2                     1       2       0.0   
94019                         0                     1       2       0.0   
39004                         0                     4       2       0.0   
13463                         1                     4       1       0.0   

        babies  previous_cancellations  previous_bookings_not_canceled  ...  \
62810        0                       0                               0  ...   
60440        0                       0                               0  ...   
118566       0                       0                               0  ...   
65878        0                       0                               0  ...   
103778       0                       0                               0  ...   
...        ...                     ...                             ...  ...   
67049        0                       0                               0  ...   
108930       0                       0                               0  ...   
94019        0                       0                               0  ...   
39004        0                       0                               0  ...   
13463        0                       0                               0  ...   

        agent-510.0  agent-526.0  agent-527.0  agent-531.0  agent-535.0  \
62810             0            0            0            0            0   
60440             0            0            0            0            0   
118566            0            0            0            0            0   
65878             0            0            0            0            0   
103778            0            0            0            0            0   
...             ...          ...          ...          ...          ...   
67049             0            0            0            0            0   
108930            0            0            0            0            0   
94019             0            0            0            0            0   
39004             0            0            0            0            0   
13463             0            0            0            0            0   

        customer_type-Group  customer_type-Transient  \
62810                     0                        1   
60440                     0                        1   
118566                    0                        1   
65878                     0                        1   
103778                    0                        1   
...                     ...                      ...   
67049                     0                        1   
1089

In [29]:
from sklearn.linear_model import LogisticRegression            # making logistic regression model

In [30]:
logistic=LogisticRegression()

In [31]:
logistic.fit(X_train,y_train)

C:\Users\Abhishek saurabh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
y_pred= logistic.predict(X_test)           # #predicting the test data

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [34]:
accuracy_score(y_test,y_pred)                   # Here is our predicted value 

0.9557611568962836

In [38]:
# Now using different algorithms to find accuracy

In [39]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.96      0.97      0.96     15773\n           1       0.95      0.93      0.94      9951\n\n    accuracy                           0.96     25724\n   macro avg       0.96      0.95      0.95     25724\nweighted avg       0.96      0.96      0.96     25724\n'

In [40]:
#calculating the ROC and AUC  for the logistics regression


In [41]:
from sklearn.metrics import roc_curve,roc_auc_score

In [42]:
roc_curve(y_test,y_pred)

(array([0.        , 0.02910036, 1.        ]),
 array([0.        , 0.93176565, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [43]:
roc_auc_score(y_test,y_pred)

0.9513326451581301

In [44]:
# Using Random forest algorithm

In [45]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

In [46]:
rand=RandomForestClassifier(n_jobs=10, random_state=40)

In [47]:
gb=GradientBoostingClassifier(random_state=50)

In [48]:
rand.fit(X_train,y_train)

RandomForestClassifier(n_jobs=10, random_state=40)

In [49]:
gb.fit(X_train,y_train)

GradientBoostingClassifier(random_state=50)

In [50]:
# predicting the test sample for randomforest and gradient boosting 
rand_pred=rand.predict(X_test)

In [51]:
gb_pred=gb.predict(X_test)

In [52]:
accuracy_score(y_test,rand_pred)

1.0

In [53]:
accuracy_score(y_test,gb_pred)

1.0

In [54]:
classification_report(y_test,rand_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     15773\n           1       1.00      1.00      1.00      9951\n\n    accuracy                           1.00     25724\n   macro avg       1.00      1.00      1.00     25724\nweighted avg       1.00      1.00      1.00     25724\n'

In [55]:
classification_report(y_test,gb_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     15773\n           1       1.00      1.00      1.00      9951\n\n    accuracy                           1.00     25724\n   macro avg       1.00      1.00      1.00     25724\nweighted avg       1.00      1.00      1.00     25724\n'

In [56]:
roc_auc_score(y_test,rand_pred)

1.0

In [57]:
roc_auc_score(y_test,gb_pred)

1.0

In [ ]:
#Using  confusion matrix for logistic reression,random forest and gradient boosting


In [58]:
from sklearn.metrics import confusion_matrix

In [59]:
confusion_matrix(y_test,y_pred)

array([[15314,   459],
       [  679,  9272]], dtype=int64)

In [60]:
confusion_matrix(y_test,rand_pred)

array([[15773,     0],
       [    0,  9951]], dtype=int64)

In [61]:
confusion_matrix(y_test,gb_pred)

array([[15773,     0],
       [    0,  9951]], dtype=int64)

#  from all three algorithm we will found that random forest and gradient boosting gives maximum accuracy